
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/web?serverTimezone=UTC
    username: root
    password: liuyang123456
  jpa:
    database: mysql
    show-sql: false
  #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    timeBetweenEvictionRunsMillis: 30000
    testOnBorrow: true
    testWhileIdle: true


server:
  port: 8087


